const moduloA = require('./modulaa')
const moduloB = require('./modudob')
console.log(moduloA.ola)
console.log(moduloA.bemVindo)
console.log(moduloA.ateLogo)
console.log(moduloA)
console.log(moduloB.bomDia)
console.log(moduloB.boanoite())
console.log(moduloB)